import { useEffect, useMemo, useRef, useState } from 'react'
import { AppShell } from '../components/AppShell'
import { useAuth } from '../auth/AuthContext'
import { useWorkspace } from '../workspace/WorkspaceContext'
import { deleteWorkspaceDocument, downloadWorkspaceDocument, fetchWorkspaceDocuments, getWorkspaceDocumentUrl, openWorkspaceDocument, uploadWorkspaceDocument, type WorkspaceDocument } from '../lib/documentos'

const categories = ['General', 'Finanzas', 'Propuestas', 'Actas', 'Imágenes', 'Otros']
const formatSize = (bytes?: number) => bytes == null ? '' : bytes < 1024 ? `${bytes} B` : bytes < 1048576 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1048576).toFixed(1)} MB`

export function DocumentosPage() {
  const { profile } = useAuth(); const { workspace } = useWorkspace(); const fileInput = useRef<HTMLInputElement>(null)
  const [documents, setDocuments] = useState<WorkspaceDocument[]>([]); const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState(''); const [source, setSource] = useState('Todos'); const [type, setType] = useState('Todos'); const [status, setStatus] = useState('')
  const [preview, setPreview] = useState<{ document: WorkspaceDocument; url: string } | null>(null); const [opening, setOpening] = useState<string | null>(null)
  const [uploading, setUploading] = useState(false); const [uploadCategory, setUploadCategory] = useState('General')
  const canManage = profile?.rol === 'Administrador' || profile?.rol === 'Coordinador'
  async function load() { if (!profile || !workspace) return; setLoading(true); try { setDocuments(await fetchWorkspaceDocuments(workspace.id_espacio, profile.idUsuario)); setStatus('') } catch (error) { setStatus(error instanceof Error ? error.message : 'No fue posible cargar los documentos.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [profile?.idUsuario, workspace?.id_espacio])
  const fileType = (doc: WorkspaceDocument) => doc.mimeType.includes('pdf') || doc.name.toLowerCase().endsWith('.pdf') ? 'PDF' : doc.mimeType.startsWith('image/') ? 'Imagen' : 'Otro'
  const filtered = useMemo(() => documents.filter((doc) => (source === 'Todos' || doc.source === source) && (type === 'Todos' || fileType(doc) === type) && `${doc.name} ${doc.context} ${doc.author} ${doc.category ?? ''}`.toLowerCase().includes(search.toLowerCase())), [documents, search, source, type])
  async function showPreview(doc: WorkspaceDocument) { setOpening(doc.id); setStatus(''); try { setPreview({ document: doc, url: await getWorkspaceDocumentUrl(doc.path, doc.bucket) }) } catch (error) { setStatus(error instanceof Error ? error.message : 'No fue posible abrir la vista previa.') } finally { setOpening(null) } }
  async function download(doc: WorkspaceDocument) { setOpening(doc.id); setStatus(''); try { await downloadWorkspaceDocument(doc.path, doc.name, doc.bucket) } catch (error) { setStatus(error instanceof Error ? error.message : 'No fue posible descargar el archivo.') } finally { setOpening(null) } }
  async function upload(file?: File) { if (!file || !profile || !workspace) return; setUploading(true); setStatus(''); try { await uploadWorkspaceDocument(file, workspace.id_espacio, profile.idUsuario, uploadCategory); setStatus('Archivo subido correctamente.'); if (fileInput.current) fileInput.current.value = ''; await load() } catch (error) { setStatus(error instanceof Error ? error.message : 'No fue posible subir el archivo.') } finally { setUploading(false) } }
  async function remove(doc: WorkspaceDocument) { if (!window.confirm(`¿Eliminar ${doc.name}? Esta acción no se puede deshacer.`)) return; setOpening(doc.id); try { await deleteWorkspaceDocument(doc); setPreview(null); await load() } catch (error) { setStatus(error instanceof Error ? error.message : 'No fue posible eliminar el archivo.') } finally { setOpening(null) } }
  return <AppShell title="Documentos" subtitle={`Archivos compartidos dentro de ${workspace?.nombre ?? 'tu espacio de trabajo'}.`}>
    <section className="document-hero glass-card"><div><span className="eyebrow">Centro de documentos</span><h2>Todo lo compartido, en un solo lugar</h2><p>Repositorio y archivos de chat aislados dentro del espacio actual.</p></div><div className="document-count"><strong>{documents.length}</strong><span>archivos</span></div></section>
    <section className="document-upload glass-card"><div><span className="eyebrow">Subida directa</span><h3>Agregar al repositorio</h3><p>Hasta 20 MB por archivo. La actividad queda registrada en la bitácora.</p></div><label><span>Categoría</span><select value={uploadCategory} onChange={(event) => setUploadCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label className={`primary-button file-button${uploading ? ' disabled' : ''}`}>{uploading ? 'Subiendo…' : '+ Seleccionar archivo'}<input ref={fileInput} type="file" disabled={uploading} onChange={(event) => void upload(event.target.files?.[0])}/></label></section>
    <section className="document-toolbar glass-card"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por archivo, persona o categoría"/><select value={source} onChange={(event) => setSource(event.target.value)}><option>Todos</option><option>Repositorio</option><option>Chat general</option><option>Chat privado</option></select><select value={type} onChange={(event) => setType(event.target.value)}><option>Todos</option><option>PDF</option><option>Imagen</option><option>Otro</option></select><button className="ghost-button" onClick={() => void load()}>Actualizar</button></section>
    {status ? <div className="form-status">{status}</div> : null}
    {loading ? <div className="glass-card empty-state">Cargando documentos…</div> : filtered.length ? <section className="document-grid">{filtered.map((doc) => <article className="document-card glass-card" key={doc.id}><div className={`document-icon ${fileType(doc).toLowerCase()}`}>{fileType(doc) === 'Imagen' ? 'IMG' : fileType(doc)}</div><div className="document-info"><span className="eyebrow">{doc.source} {doc.category ? `· ${doc.category}` : ''}</span><h3 title={doc.name}>{doc.name}</h3><p>{doc.context}</p><small>Por {doc.author} · {formatSize(doc.size)}{doc.size ? ' · ' : ''}{new Intl.DateTimeFormat('es-CR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(doc.createdAt))}</small></div><div className="document-actions">{fileType(doc) !== 'Otro' ? <button className="primary-button" disabled={opening === doc.id} onClick={() => void showPreview(doc)}>{opening === doc.id ? 'Abriendo…' : 'Vista previa'}</button> : <button className="primary-button" onClick={() => void openWorkspaceDocument(doc.path, doc.bucket)}>Abrir</button>}<button className="ghost-button" disabled={opening === doc.id} onClick={() => void download(doc)}>Descargar</button>{doc.source === 'Repositorio' && (canManage || doc.uploaderId === profile?.idUsuario) ? <button className="ghost-button danger" disabled={opening === doc.id} onClick={() => void remove(doc)}>Eliminar</button> : null}</div></article>)}</section> : <div className="glass-card empty-state">No hay archivos que coincidan con los filtros.</div>}
    {preview ? <div className="document-modal-backdrop" role="presentation" onMouseDown={() => setPreview(null)}><section className="document-modal" role="dialog" aria-modal="true" aria-label={`Vista previa de ${preview.document.name}`} onMouseDown={(event) => event.stopPropagation()}><header><div><span className="eyebrow">Vista previa</span><h3>{preview.document.name}</h3></div><button type="button" className="document-modal-close" onClick={() => setPreview(null)} aria-label="Cerrar">×</button></header><div className="document-preview">{fileType(preview.document) === 'Imagen' ? <img src={preview.url} alt={preview.document.name}/> : <iframe src={preview.url} title={preview.document.name}/>}</div><footer><button className="ghost-button" onClick={() => void openWorkspaceDocument(preview.document.path, preview.document.bucket)}>Abrir en otra pestaña</button><button className="primary-button" onClick={() => void download(preview.document)}>Descargar</button></footer></section></div> : null}
  </AppShell>
}
