import { useEffect,useState,type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext'
import { createEspacio,fetchEspacios,fetchMisSolicitudesEspacio,solicitarEspacio,type EspacioTrabajo,type SolicitudEspacio } from '../lib/espacios'
import { useWorkspace } from '../workspace/WorkspaceContext'
export function SeleccionarEspacioPage(){const{profile,signOut}=useAuth();const{workspaces,selectWorkspace,refresh}=useWorkspace();const[all,setAll]=useState<EspacioTrabajo[]>([]);const[requests,setRequests]=useState<SolicitudEspacio[]>([]);const[status,setStatus]=useState('');const[showCreate,setShowCreate]=useState(false);const[name,setName]=useState('');const[description,setDescription]=useState('');const[creating,setCreating]=useState(false);const navigate=useNavigate();const canCreate=profile?.rol==='Administrador'||profile?.rol==='Coordinador'
 useEffect(()=>{if(!profile)return;void Promise.all([fetchEspacios(),fetchMisSolicitudesEspacio(profile.idUsuario)]).then(([spaces,rows])=>{setAll(spaces);setRequests(rows)})},[profile])
 function enter(space:EspacioTrabajo){selectWorkspace(space);navigate('/dashboard',{replace:true})}
 async function request(space:EspacioTrabajo){if(!profile)return;try{await solicitarEspacio(space.id_espacio,profile.idUsuario);setStatus('Solicitud enviada correctamente.');setRequests(await fetchMisSolicitudesEspacio(profile.idUsuario));await refresh()}catch(error){setStatus(error instanceof Error?error.message:'No fue posible enviar la solicitud.')}}
 async function handleCreate(event:FormEvent){event.preventDefault();if(!profile||!canCreate||!name.trim())return;setCreating(true);setStatus('');try{const created=await createEspacio(name,description,profile.idUsuario,profile.rol as 'Administrador'|'Coordinador');await refresh();setAll(await fetchEspacios());setShowCreate(false);setName('');setDescription('');selectWorkspace(created);navigate('/dashboard',{replace:true})}catch(error){setStatus(error instanceof Error?error.message:'No fue posible crear el espacio.')}finally{setCreating(false)}}
 return<div className="workspace-select-page"><section><div className="workspace-topbar"><span className="brand-kicker">SIGECOM</span><div>{canCreate?<button className="ghost-button" onClick={()=>setShowCreate((value)=>!value)}>{showCreate?'Cancelar':'+ Crear espacio'}</button>:null}<button className="ghost-button" onClick={()=>void signOut()}>Cerrar sesión</button></div></div><h1>Selecciona tu espacio de trabajo</h1><p>Todo el contenido de SIGECOM se organizará dentro del espacio seleccionado.</p>{status?<div className="form-status">{status}</div>:null}{showCreate?<form className="workspace-create-form" onSubmit={(event)=>void handleCreate(event)}><label><span>Nombre</span><input value={name} placeholder="Ej. GEN 27" maxLength={100} onChange={(event)=>setName(event.target.value)} required/></label><label><span>Descripción</span><input value={description} placeholder="Descripción del espacio" onChange={(event)=>setDescription(event.target.value)}/></label><button className="primary-button" disabled={creating}>{creating?'Creando…':'Crear y entrar'}</button></form>:null}<div className="workspace-cards">{all.map((space)=>{const allowed=workspaces.some((x)=>x.id_espacio===space.id_espacio);const pending=requests.find((x)=>x.id_espacio===space.id_espacio&&x.estado==='pendiente');return<article key={space.id_espacio}><span>ESPACIO DE TRABAJO</span><h2>{space.nombre}</h2><p>{space.descripcion}</p>{allowed?<button className="primary-button" onClick={()=>enter(space)}>Entrar a {space.nombre}</button>:<button className="ghost-button" disabled={Boolean(pending)} onClick={()=>void request(space)}>{pending?'Solicitud pendiente':'Solicitar acceso'}</button>}</article>})}</div></section></div>}
