import { useEffect,useState } from 'react'
import { AppShell } from '../components/AppShell'
import { LoadingState } from '../components/LoadingState'
import { shortDate } from '../lib/format'
import { fetchWorkspaceRequests,resolveWorkspaceRequest,type WorkspaceRequest } from '../lib/solicitudesEspacio'
import { useWorkspace } from '../workspace/WorkspaceContext'
export function SolicitudesEspacioPage(){const{workspace}=useWorkspace();const[requests,setRequests]=useState<WorkspaceRequest[]>([]);const[roles,setRoles]=useState<Record<number,'Coordinador'|'Miembro'>>({});const[loading,setLoading]=useState(true);const[processing,setProcessing]=useState(0);const[status,setStatus]=useState('')
 async function load(){if(!workspace)return;setLoading(true);try{setRequests(await fetchWorkspaceRequests(workspace.id_espacio))}catch(error){setStatus(error instanceof Error?error.message:'No fue posible cargar las solicitudes.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[workspace?.id_espacio])
 async function resolve(request:WorkspaceRequest,state:'aprobada'|'rechazada'){setProcessing(request.id_solicitud);setStatus('');try{await resolveWorkspaceRequest(request.id_solicitud,state,roles[request.id_solicitud]??'Miembro');setStatus(state==='aprobada'?'Miembro incorporado correctamente.':'Solicitud rechazada.');await load()}catch(error){setStatus(error instanceof Error?error.message:'No fue posible resolver la solicitud.')}finally{setProcessing(0)}}
 return<AppShell title="Solicitudes de acceso" subtitle={`Administra quién puede ingresar a ${workspace?.nombre??'este espacio'}.`}><div className="stats-grid"><article className="stat-card accent-gold"><span>Pendientes</span><strong>{loading?'…':requests.length}</strong></article><article className="stat-card accent-blue"><span>Espacio</span><strong className="small-metric">{workspace?.nombre}</strong></article></div><section className="glass-card"><div className="section-head"><div><span className="eyebrow">Miembros</span><h3>Solicitudes pendientes</h3></div><button className="ghost-button" onClick={()=>void load()}>Actualizar</button></div>{status?<div className="form-status">{status}</div>:null}{loading?<LoadingState/>:null}{!loading&&!requests.length?<div className="empty-state">No hay solicitudes pendientes para este espacio.</div>:null}<div className="workspace-request-list">{requests.map((request)=><article className="workspace-request-card" key={request.id_solicitud}><span className="message-avatar">{request.usuario?.avatar_url?<img src={request.usuario.avatar_url} alt=""/>:request.usuario?.nombre.charAt(0)??'U'}</span><div><strong>{request.usuario?.nombre??'Usuario'}</strong><span>{request.usuario?.correo}</span><small>Solicitada: {shortDate(request.fecha_solicitud)}</small></div><select value={roles[request.id_solicitud]??'Miembro'} onChange={(event)=>setRoles((current)=>({...current,[request.id_solicitud]:event.target.value as 'Coordinador'|'Miembro'}))}><option value="Miembro">Miembro</option><option value="Coordinador">Coordinador</option></select><div className="row-actions"><button className="primary-button" disabled={processing===request.id_solicitud} onClick={()=>void resolve(request,'aprobada')}>Aprobar</button><button className="ghost-button" disabled={processing===request.id_solicitud} onClick={()=>void resolve(request,'rechazada')}>Rechazar</button></div></article>)}</div></section></AppShell>}
