create table if not exists public.mensajes_privados (id_mensaje bigint generated by default as identity primary key,id_remitente bigint not null references public.usuarios(id_usuario) on delete cascade,id_destinatario bigint not null references public.usuarios(id_usuario) on delete cascade,contenido text not null,fecha_envio timestamptz not null default now(),leido boolean not null default false,constraint mensajes_privados_distintos_chk check(id_remitente<>id_destinatario),constraint mensajes_privados_contenido_chk check(char_length(trim(contenido)) between 1 and 1000));
create index if not exists idx_mensajes_privados_conversacion on public.mensajes_privados(id_remitente,id_destinatario,fecha_envio desc);
alter table public.mensajes_privados enable row level security;
create policy mensajes_privados_select_participantes on public.mensajes_privados for select to authenticated using(id_remitente=public.get_current_internal_user_id() or id_destinatario=public.get_current_internal_user_id());
create policy mensajes_privados_insert_remitente on public.mensajes_privados for insert to authenticated with check(id_remitente=public.get_current_internal_user_id() and id_destinatario<>id_remitente);
grant select,insert on public.mensajes_privados to authenticated;
grant usage,select on sequence public.mensajes_privados_id_mensaje_seq to authenticated;
