create table if not exists public.reuniones (
  id_reunion bigint generated by default as identity primary key,
  id_espacio bigint not null references public.espacios_trabajo(id_espacio) on delete cascade,
  titulo varchar(140) not null check (char_length(trim(titulo)) between 3 and 140),
  descripcion text null check (descripcion is null or char_length(descripcion) <= 1000),
  fecha_inicio timestamptz not null,
  enlace_meet text not null check (enlace_meet ~ '^https://meet\.google\.com/[a-z]{3}-[a-z]{4}-[a-z]{3}([/?].*)?$'),
  creado_por bigint not null references public.usuarios(id_usuario),
  fecha_creacion timestamptz not null default now()
);
create index if not exists reuniones_espacio_fecha_idx on public.reuniones(id_espacio, fecha_inicio);
alter table public.reuniones enable row level security;
grant select, insert, update, delete on public.reuniones to authenticated;
grant usage, select on sequence public.reuniones_id_reunion_seq to authenticated;

create policy reuniones_select_miembros on public.reuniones for select to authenticated
using (public.is_espacio_member(id_espacio));

create policy reuniones_insert_gestores on public.reuniones for insert to authenticated
with check (creado_por = public.get_current_internal_user_id() and exists (
  select 1 from public.espacio_miembros em where em.id_espacio = reuniones.id_espacio
  and em.id_usuario = public.get_current_internal_user_id() and em.activo
  and em.rol_espacio in ('Administrador', 'Coordinador')
));

create policy reuniones_update_gestores on public.reuniones for update to authenticated
using (exists (select 1 from public.espacio_miembros em where em.id_espacio = reuniones.id_espacio
  and em.id_usuario = public.get_current_internal_user_id() and em.activo
  and em.rol_espacio in ('Administrador', 'Coordinador')))
with check (exists (select 1 from public.espacio_miembros em where em.id_espacio = reuniones.id_espacio
  and em.id_usuario = public.get_current_internal_user_id() and em.activo
  and em.rol_espacio in ('Administrador', 'Coordinador')));

create policy reuniones_delete_gestores on public.reuniones for delete to authenticated
using (exists (select 1 from public.espacio_miembros em where em.id_espacio = reuniones.id_espacio
  and em.id_usuario = public.get_current_internal_user_id() and em.activo
  and em.rol_espacio in ('Administrador', 'Coordinador')));
