create table if not exists public.mensajes_comision (
    id_mensaje bigint generated by default as identity primary key,
    id_comision bigint not null references public.comisiones (id_comision) on delete cascade,
    id_usuario bigint not null references public.usuarios (id_usuario) on delete cascade,
    contenido text not null,
    fecha_envio timestamptz not null default now(),
    constraint mensajes_comision_contenido_chk check (char_length(trim(contenido)) between 1 and 1000)
);
create index if not exists idx_mensajes_comision_sala_fecha on public.mensajes_comision (id_comision, fecha_envio desc);
alter table public.mensajes_comision enable row level security;
drop policy if exists mensajes_select_participantes on public.mensajes_comision;
create policy mensajes_select_participantes on public.mensajes_comision for select to authenticated
using (public.is_comision_member(id_comision) or public.is_admin_or_coordinator());
drop policy if exists mensajes_insert_participantes on public.mensajes_comision;
create policy mensajes_insert_participantes on public.mensajes_comision for insert to authenticated
with check (id_usuario = public.get_current_internal_user_id() and (public.is_comision_member(id_comision) or public.is_admin_or_coordinator()));
grant select, insert on table public.mensajes_comision to authenticated;
grant usage, select on sequence public.mensajes_comision_id_mensaje_seq to authenticated;
do $$ begin
 if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='mensajes_comision') then
  alter publication supabase_realtime add table public.mensajes_comision;
 end if;
end $$;
notify pgrst, 'reload schema';
