-- SIGECOM - Fase 2
-- Esquema limpio para ejecutar en una base vacia de Supabase/PostgreSQL

begin;

create extension if not exists pgcrypto;

-- =========================================================
-- TABLAS PRINCIPALES
-- =========================================================

create table public.roles (
    id_rol smallint generated by default as identity primary key,
    nombre varchar(50) not null unique,
    descripcion text,
    fecha_creacion timestamptz not null default now()
);

create table public.estados (
    id_estado smallint generated by default as identity primary key,
    nombre varchar(50) not null unique,
    descripcion text,
    fecha_creacion timestamptz not null default now()
);

create table public.usuarios (
    id_usuario bigint generated by default as identity primary key,
    auth_user_id uuid unique references auth.users (id) on delete cascade,
    nombre varchar(120) not null,
    correo varchar(255) not null unique,
    telefono varchar(30),
    id_rol smallint not null references public.roles (id_rol),
    activo boolean not null default true,
    fecha_creacion timestamptz not null default now(),
    fecha_actualizacion timestamptz not null default now(),
    constraint usuarios_correo_formato_chk check (position('@' in correo) > 1)
);

create table public.comisiones (
    id_comision bigint generated by default as identity primary key,
    titulo varchar(150) not null,
    descripcion text,
    fecha_inicio date not null,
    fecha_fin date,
    id_estado smallint not null references public.estados (id_estado),
    creado_por bigint references public.usuarios (id_usuario),
    fecha_creacion timestamptz not null default now(),
    fecha_actualizacion timestamptz not null default now(),
    constraint comisiones_fechas_chk check (fecha_fin is null or fecha_fin >= fecha_inicio)
);

create table public.comision_miembros (
    id_comision bigint not null references public.comisiones (id_comision) on delete cascade,
    id_usuario bigint not null references public.usuarios (id_usuario) on delete cascade,
    puede_votar boolean not null default true,
    es_responsable boolean not null default false,
    activo boolean not null default true,
    fecha_asignacion timestamptz not null default now(),
    primary key (id_comision, id_usuario)
);

create table public.presupuestos (
    id_presupuesto bigint generated by default as identity primary key,
    id_comision bigint not null unique references public.comisiones (id_comision) on delete cascade,
    monto_estimado numeric(12, 2) not null default 0,
    monto_aprobado numeric(12, 2) default 0,
    fecha_aprobacion date,
    observaciones text,
    creado_por bigint references public.usuarios (id_usuario),
    fecha_creacion timestamptz not null default now(),
    fecha_actualizacion timestamptz not null default now(),
    constraint presupuestos_monto_estimado_chk check (monto_estimado >= 0),
    constraint presupuestos_monto_aprobado_chk check (monto_aprobado is null or monto_aprobado >= 0)
);

create table public.movimientos_financieros (
    id_movimiento bigint generated by default as identity primary key,
    id_comision bigint not null references public.comisiones (id_comision) on delete cascade,
    tipo varchar(20) not null,
    monto numeric(12, 2) not null,
    descripcion text not null,
    fecha timestamptz not null default now(),
    creado_por bigint references public.usuarios (id_usuario),
    fecha_creacion timestamptz not null default now(),
    constraint movimientos_tipo_chk check (tipo in ('ingreso', 'gasto')),
    constraint movimientos_monto_chk check (monto > 0)
);

create table public.propuestas (
    id_propuesta bigint generated by default as identity primary key,
    id_comision bigint not null references public.comisiones (id_comision) on delete cascade,
    titulo varchar(150) not null,
    descripcion text not null,
    fecha_creacion timestamptz not null default now(),
    estado varchar(20) not null default 'pendiente',
    resultado_final varchar(20) not null default 'pendiente',
    fecha_cierre timestamptz,
    creada_por bigint references public.usuarios (id_usuario),
    constraint propuestas_estado_chk check (estado in ('pendiente', 'aprobada', 'rechazada', 'cerrada')),
    constraint propuestas_resultado_chk check (resultado_final in ('pendiente', 'aprobada', 'rechazada', 'empate'))
);

create table public.votos (
    id_voto bigint generated by default as identity primary key,
    id_propuesta bigint not null references public.propuestas (id_propuesta) on delete cascade,
    id_usuario bigint not null references public.usuarios (id_usuario) on delete cascade,
    voto varchar(20) not null,
    fecha timestamptz not null default now(),
    constraint votos_tipo_chk check (voto in ('a_favor', 'en_contra', 'abstencion')),
    constraint votos_unicos_por_usuario unique (id_propuesta, id_usuario)
);

create table public.reportes (
    id_reporte bigint generated by default as identity primary key,
    id_comision bigint references public.comisiones (id_comision) on delete set null,
    generado_por bigint not null references public.usuarios (id_usuario),
    tipo varchar(50) not null default 'general',
    fecha_generacion timestamptz not null default now(),
    descripcion text,
    constraint reportes_tipo_chk check (tipo in ('presupuestos', 'financiero', 'propuestas', 'actividad_comisiones', 'general'))
);

create table public.notificaciones (
    id_notificacion bigint generated by default as identity primary key,
    id_usuario bigint not null references public.usuarios (id_usuario) on delete cascade,
    mensaje text not null,
    leida boolean not null default false,
    tipo varchar(50) not null default 'informativa',
    fecha_envio timestamptz not null default now()
);

create table public.archivos (
    id_archivo bigint generated by default as identity primary key,
    id_comision bigint references public.comisiones (id_comision) on delete cascade,
    id_propuesta bigint references public.propuestas (id_propuesta) on delete cascade,
    nombre varchar(255) not null,
    bucket varchar(100) not null default 'sigecom-archivos',
    ruta_storage text not null unique,
    url text,
    mime_type varchar(100),
    tamano_bytes bigint,
    fecha_subida timestamptz not null default now(),
    subido_por bigint references public.usuarios (id_usuario),
    constraint archivos_relacion_chk check (id_comision is not null or id_propuesta is not null),
    constraint archivos_tamano_chk check (tamano_bytes is null or tamano_bytes >= 0)
);

create table public.historial_cambios (
    id_historial bigint generated by default as identity primary key,
    tabla_afectada varchar(100) not null,
    id_registro bigint not null,
    accion varchar(30) not null,
    realizado_por bigint references public.usuarios (id_usuario),
    descripcion text,
    fecha timestamptz not null default now(),
    constraint historial_accion_chk check (
        accion in ('INSERT', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'CAMBIO_ESTADO', 'VOTO', 'SUBIDA_ARCHIVO')
    )
);

-- =========================================================
-- INDICES
-- =========================================================

create index idx_usuarios_auth_user_id on public.usuarios (auth_user_id);
create index idx_usuarios_id_rol on public.usuarios (id_rol);
create index idx_comisiones_estado on public.comisiones (id_estado);
create index idx_comisiones_fechas on public.comisiones (fecha_inicio, fecha_fin);
create index idx_comision_miembros_usuario on public.comision_miembros (id_usuario);
create index idx_presupuestos_comision on public.presupuestos (id_comision);
create index idx_movimientos_comision_fecha on public.movimientos_financieros (id_comision, fecha desc);
create index idx_movimientos_tipo on public.movimientos_financieros (tipo);
create index idx_propuestas_comision_estado on public.propuestas (id_comision, estado);
create index idx_votos_propuesta on public.votos (id_propuesta);
create index idx_reportes_comision_tipo on public.reportes (id_comision, tipo);
create index idx_notificaciones_usuario_leida on public.notificaciones (id_usuario, leida, fecha_envio desc);
create index idx_archivos_comision on public.archivos (id_comision);
create index idx_archivos_propuesta on public.archivos (id_propuesta);
create index idx_historial_tabla_registro_fecha on public.historial_cambios (tabla_afectada, id_registro, fecha desc);

-- =========================================================
-- DATOS INICIALES
-- =========================================================

insert into public.roles (nombre, descripcion) values
    ('Administrador', 'Acceso total al sistema y configuracion general.'),
    ('Coordinador', 'Gestiona comisiones, presupuestos, propuestas y seguimiento.'),
    ('Miembro', 'Participa en comisiones, vota y consulta informacion segun permisos.');

insert into public.estados (nombre, descripcion) values
    ('Pendiente', 'La comision aun no ha iniciado formalmente.'),
    ('En Proceso', 'La comision se encuentra en ejecucion.'),
    ('Finalizada', 'La comision concluyo sus actividades.'),
    ('Cancelada', 'La comision fue suspendida o anulada.');

-- =========================================================
-- FUNCIONES AUXILIARES
-- =========================================================

create or replace function public.set_fecha_actualizacion()
returns trigger
language plpgsql
as $$
begin
    new.fecha_actualizacion = now();
    return new;
end;
$$;

create or replace function public.get_current_internal_user_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
    select u.id_usuario
    from public.usuarios u
    where u.auth_user_id = auth.uid()
      and u.activo = true
    limit 1;
$$;

create or replace function public.user_has_role(target_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce((
        select r.nombre = any(target_roles)
        from public.usuarios u
        join public.roles r on r.id_rol = u.id_rol
        where u.auth_user_id = auth.uid()
          and u.activo = true
        limit 1
    ), false);
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select public.user_has_role(array['Administrador']);
$$;

create or replace function public.is_admin_or_coordinator()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select public.user_has_role(array['Administrador', 'Coordinador']);
$$;

create or replace function public.is_comision_member(p_id_comision bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce((
        select true
        from public.comision_miembros cm
        where cm.id_comision = p_id_comision
          and cm.id_usuario = public.get_current_internal_user_id()
          and cm.activo = true
        limit 1
    ), false);
$$;

create or replace function public.get_comision_id_from_propuesta(p_id_propuesta bigint)
returns bigint
language sql
stable
security definer
set search_path = public
as $$
    select p.id_comision
    from public.propuestas p
    where p.id_propuesta = p_id_propuesta
    limit 1;
$$;

create or replace function public.can_vote_on_propuesta(p_id_propuesta bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select
        public.is_admin_or_coordinator()
        or exists (
            select 1
            from public.propuestas p
            join public.comision_miembros cm
                on cm.id_comision = p.id_comision
               and cm.id_usuario = public.get_current_internal_user_id()
               and cm.activo = true
               and cm.puede_votar = true
            where p.id_propuesta = p_id_propuesta
              and p.estado = 'pendiente'
        );
$$;

create or replace function public.can_manage_archivo(p_id_comision bigint, p_id_propuesta bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select
        public.is_admin_or_coordinator()
        or (
            p_id_comision is not null
            and public.is_comision_member(p_id_comision)
        )
        or (
            p_id_propuesta is not null
            and public.is_comision_member(public.get_comision_id_from_propuesta(p_id_propuesta))
        );
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_id_rol_miembro smallint;
    v_nombre text;
begin
    select id_rol
    into v_id_rol_miembro
    from public.roles
    where nombre = 'Miembro'
    limit 1;

    v_nombre := coalesce(
        new.raw_user_meta_data ->> 'nombre',
        new.raw_user_meta_data ->> 'full_name',
        split_part(new.email, '@', 1)
    );

    insert into public.usuarios (
        auth_user_id,
        nombre,
        correo,
        telefono,
        id_rol,
        activo
    )
    values (
        new.id,
        v_nombre,
        new.email,
        new.raw_user_meta_data ->> 'telefono',
        v_id_rol_miembro,
        true
    );

    return new;
end;
$$;

create or replace function public.handle_updated_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.usuarios
       set correo = coalesce(new.email, correo),
           fecha_actualizacion = now()
     where auth_user_id = new.id;

    return new;
end;
$$;

create or replace function public.registrar_historial_generico()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_payload jsonb;
    v_id_registro bigint;
begin
    v_payload := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
    v_id_registro := coalesce(nullif(v_payload ->> tg_argv[0], ''), '0')::bigint;

    insert into public.historial_cambios (
        tabla_afectada,
        id_registro,
        accion,
        realizado_por,
        descripcion
    )
    values (
        tg_table_name,
        v_id_registro,
        tg_op,
        public.get_current_internal_user_id(),
        coalesce(tg_argv[1], tg_table_name || ' ' || lower(tg_op))
    );

    return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create or replace function public.registrar_cambio_estado_comision()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.id_estado is distinct from old.id_estado then
        insert into public.historial_cambios (
            tabla_afectada,
            id_registro,
            accion,
            realizado_por,
            descripcion
        )
        values (
            'comisiones',
            new.id_comision,
            'CAMBIO_ESTADO',
            public.get_current_internal_user_id(),
            'Cambio de estado de la comision'
        );
    end if;

    return new;
end;
$$;

create or replace function public.registrar_voto_historial()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.historial_cambios (
        tabla_afectada,
        id_registro,
        accion,
        realizado_por,
        descripcion
    )
    values (
        'votos',
        new.id_voto,
        'VOTO',
        new.id_usuario,
        'Registro de voto en propuesta'
    );

    return new;
end;
$$;

create or replace function public.registrar_subida_archivo_historial()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.historial_cambios (
        tabla_afectada,
        id_registro,
        accion,
        realizado_por,
        descripcion
    )
    values (
        'archivos',
        new.id_archivo,
        'SUBIDA_ARCHIVO',
        new.subido_por,
        'Carga de archivo al sistema'
    );

    return new;
end;
$$;

create or replace function public.actualizar_resultado_propuesta(p_id_propuesta bigint)
returns table (
    id_propuesta bigint,
    votos_a_favor integer,
    votos_en_contra integer,
    abstenciones integer,
    resultado_calculado varchar(20)
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_favor integer;
    v_contra integer;
    v_abstencion integer;
    v_resultado varchar(20);
begin
    select
        count(*) filter (where voto = 'a_favor'),
        count(*) filter (where voto = 'en_contra'),
        count(*) filter (where voto = 'abstencion')
    into v_favor, v_contra, v_abstencion
    from public.votos
    where public.votos.id_propuesta = p_id_propuesta;

    if v_favor > v_contra then
        v_resultado := 'aprobada';
    elsif v_contra > v_favor then
        v_resultado := 'rechazada';
    else
        v_resultado := 'empate';
    end if;

    update public.propuestas
       set resultado_final = v_resultado,
           estado = case
               when v_resultado = 'aprobada' then 'aprobada'
               when v_resultado = 'rechazada' then 'rechazada'
               else estado
           end,
           fecha_cierre = case
               when v_resultado in ('aprobada', 'rechazada') then coalesce(fecha_cierre, now())
               else fecha_cierre
           end
     where public.propuestas.id_propuesta = p_id_propuesta;

    return query
    select p_id_propuesta, v_favor, v_contra, v_abstencion, v_resultado;
end;
$$;

-- =========================================================
-- TRIGGERS
-- =========================================================

drop trigger if exists on_auth_user_created on auth.users;
drop trigger if exists on_auth_user_updated on auth.users;

create trigger trg_usuarios_set_fecha_actualizacion
before update on public.usuarios
for each row
execute function public.set_fecha_actualizacion();

create trigger trg_comisiones_set_fecha_actualizacion
before update on public.comisiones
for each row
execute function public.set_fecha_actualizacion();

create trigger trg_presupuestos_set_fecha_actualizacion
before update on public.presupuestos
for each row
execute function public.set_fecha_actualizacion();

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_auth_user();

create trigger on_auth_user_updated
after update of email on auth.users
for each row
execute function public.handle_updated_auth_user();

create trigger trg_historial_comisiones
after insert or update or delete on public.comisiones
for each row
execute function public.registrar_historial_generico('id_comision', 'Operacion sobre comisiones');

create trigger trg_cambio_estado_comision
after update of id_estado on public.comisiones
for each row
execute function public.registrar_cambio_estado_comision();

create trigger trg_historial_presupuestos
after insert or update or delete on public.presupuestos
for each row
execute function public.registrar_historial_generico('id_presupuesto', 'Operacion sobre presupuestos');

create trigger trg_historial_movimientos
after insert or update or delete on public.movimientos_financieros
for each row
execute function public.registrar_historial_generico('id_movimiento', 'Operacion sobre movimientos financieros');

create trigger trg_historial_propuestas
after insert or update or delete on public.propuestas
for each row
execute function public.registrar_historial_generico('id_propuesta', 'Operacion sobre propuestas');

create trigger trg_historial_votos
after insert on public.votos
for each row
execute function public.registrar_voto_historial();

create trigger trg_historial_archivos
after insert on public.archivos
for each row
execute function public.registrar_subida_archivo_historial();

-- =========================================================
-- VISTAS PARA REPORTES
-- =========================================================

create view public.vw_balance_comisiones as
select
    c.id_comision,
    c.titulo,
    e.nombre as estado,
    coalesce(p.monto_estimado, 0) as monto_estimado,
    coalesce(p.monto_aprobado, 0) as monto_aprobado,
    coalesce(sum(case when mf.tipo = 'ingreso' then mf.monto else 0 end), 0) as total_ingresos,
    coalesce(sum(case when mf.tipo = 'gasto' then mf.monto else 0 end), 0) as total_gastos,
    coalesce(sum(case when mf.tipo = 'ingreso' then mf.monto else 0 end), 0)
        - coalesce(sum(case when mf.tipo = 'gasto' then mf.monto else 0 end), 0) as balance_actual
from public.comisiones c
join public.estados e on e.id_estado = c.id_estado
left join public.presupuestos p on p.id_comision = c.id_comision
left join public.movimientos_financieros mf on mf.id_comision = c.id_comision
group by c.id_comision, c.titulo, e.nombre, p.monto_estimado, p.monto_aprobado;

create view public.vw_resultados_propuestas as
select
    p.id_propuesta,
    p.id_comision,
    p.titulo,
    p.estado,
    p.resultado_final,
    count(v.id_voto) filter (where v.voto = 'a_favor') as votos_a_favor,
    count(v.id_voto) filter (where v.voto = 'en_contra') as votos_en_contra,
    count(v.id_voto) filter (where v.voto = 'abstencion') as abstenciones,
    case
        when count(v.id_voto) filter (where v.voto = 'a_favor')
           > count(v.id_voto) filter (where v.voto = 'en_contra') then true
        else false
    end as aprobada_por_mayoria_simple
from public.propuestas p
left join public.votos v on v.id_propuesta = p.id_propuesta
group by p.id_propuesta, p.id_comision, p.titulo, p.estado, p.resultado_final;

create view public.vw_actividad_comisiones as
select
    c.id_comision,
    c.titulo,
    count(distinct pr.id_propuesta) as cantidad_propuestas,
    count(distinct ar.id_archivo) as cantidad_archivos,
    count(distinct mf.id_movimiento) as cantidad_movimientos,
    count(distinct cm.id_usuario) as cantidad_miembros
from public.comisiones c
left join public.propuestas pr on pr.id_comision = c.id_comision
left join public.archivos ar on ar.id_comision = c.id_comision
left join public.movimientos_financieros mf on mf.id_comision = c.id_comision
left join public.comision_miembros cm on cm.id_comision = c.id_comision and cm.activo = true
group by c.id_comision, c.titulo;

-- =========================================================
-- RLS
-- =========================================================

alter table public.roles enable row level security;
alter table public.estados enable row level security;
alter table public.usuarios enable row level security;
alter table public.comisiones enable row level security;
alter table public.comision_miembros enable row level security;
alter table public.presupuestos enable row level security;
alter table public.movimientos_financieros enable row level security;
alter table public.propuestas enable row level security;
alter table public.votos enable row level security;
alter table public.reportes enable row level security;
alter table public.notificaciones enable row level security;
alter table public.archivos enable row level security;
alter table public.historial_cambios enable row level security;

create policy roles_select_authenticated
on public.roles
for select
to authenticated
using (true);

create policy estados_select_authenticated
on public.estados
for select
to authenticated
using (true);

create policy usuarios_select_own_or_staff
on public.usuarios
for select
to authenticated
using (
    auth.uid() = auth_user_id
    or public.is_admin_or_coordinator()
);

create policy usuarios_insert_self
on public.usuarios
for insert
to authenticated
with check (
    auth.uid() = auth_user_id
);

create policy usuarios_update_own_or_admin
on public.usuarios
for update
to authenticated
using (
    auth.uid() = auth_user_id
    or public.is_admin()
)
with check (
    auth.uid() = auth_user_id
    or public.is_admin()
);

create policy comisiones_select_authenticated
on public.comisiones
for select
to authenticated
using (true);

create policy comisiones_insert_staff
on public.comisiones
for insert
to authenticated
with check (public.is_admin_or_coordinator());

create policy comisiones_update_staff
on public.comisiones
for update
to authenticated
using (public.is_admin_or_coordinator())
with check (public.is_admin_or_coordinator());

create policy comisiones_delete_admin
on public.comisiones
for delete
to authenticated
using (public.is_admin());

create policy comision_miembros_select_authenticated
on public.comision_miembros
for select
to authenticated
using (
    public.is_admin_or_coordinator()
    or id_usuario = public.get_current_internal_user_id()
    or public.is_comision_member(id_comision)
);

create policy comision_miembros_insert_staff
on public.comision_miembros
for insert
to authenticated
with check (public.is_admin_or_coordinator());

create policy comision_miembros_update_staff
on public.comision_miembros
for update
to authenticated
using (public.is_admin_or_coordinator())
with check (public.is_admin_or_coordinator());

create policy comision_miembros_delete_staff
on public.comision_miembros
for delete
to authenticated
using (public.is_admin_or_coordinator());

create policy presupuestos_select_authenticated
on public.presupuestos
for select
to authenticated
using (true);

create policy presupuestos_insert_staff
on public.presupuestos
for insert
to authenticated
with check (public.is_admin_or_coordinator());

create policy presupuestos_update_staff
on public.presupuestos
for update
to authenticated
using (public.is_admin_or_coordinator())
with check (public.is_admin_or_coordinator());

create policy presupuestos_delete_admin
on public.presupuestos
for delete
to authenticated
using (public.is_admin());

create policy movimientos_select_authenticated
on public.movimientos_financieros
for select
to authenticated
using (true);

create policy movimientos_insert_staff
on public.movimientos_financieros
for insert
to authenticated
with check (public.is_admin_or_coordinator());

create policy movimientos_update_staff
on public.movimientos_financieros
for update
to authenticated
using (public.is_admin_or_coordinator())
with check (public.is_admin_or_coordinator());

create policy movimientos_delete_admin
on public.movimientos_financieros
for delete
to authenticated
using (public.is_admin());

create policy propuestas_select_authenticated
on public.propuestas
for select
to authenticated
using (true);

create policy propuestas_insert_staff
on public.propuestas
for insert
to authenticated
with check (public.is_admin_or_coordinator());

create policy propuestas_update_staff
on public.propuestas
for update
to authenticated
using (public.is_admin_or_coordinator())
with check (public.is_admin_or_coordinator());

create policy propuestas_delete_admin
on public.propuestas
for delete
to authenticated
using (public.is_admin());

create policy votos_select_authenticated
on public.votos
for select
to authenticated
using (true);

create policy votos_insert_self_if_authorized
on public.votos
for insert
to authenticated
with check (
    id_usuario = public.get_current_internal_user_id()
    and public.can_vote_on_propuesta(id_propuesta)
);

create policy votos_delete_admin
on public.votos
for delete
to authenticated
using (public.is_admin());

create policy reportes_select_authenticated
on public.reportes
for select
to authenticated
using (
    public.is_admin_or_coordinator()
    or generado_por = public.get_current_internal_user_id()
);

create policy reportes_insert_staff
on public.reportes
for insert
to authenticated
with check (
    public.is_admin_or_coordinator()
    and generado_por = public.get_current_internal_user_id()
);

create policy notificaciones_select_own_or_admin
on public.notificaciones
for select
to authenticated
using (
    id_usuario = public.get_current_internal_user_id()
    or public.is_admin_or_coordinator()
);

create policy notificaciones_insert_staff
on public.notificaciones
for insert
to authenticated
with check (public.is_admin_or_coordinator());

create policy notificaciones_update_own_or_admin
on public.notificaciones
for update
to authenticated
using (
    id_usuario = public.get_current_internal_user_id()
    or public.is_admin_or_coordinator()
)
with check (
    id_usuario = public.get_current_internal_user_id()
    or public.is_admin_or_coordinator()
);

create policy archivos_select_authenticated
on public.archivos
for select
to authenticated
using (true);

create policy archivos_insert_authorized
on public.archivos
for insert
to authenticated
with check (
    subido_por = public.get_current_internal_user_id()
    and public.can_manage_archivo(id_comision, id_propuesta)
);

create policy archivos_update_owner_or_staff
on public.archivos
for update
to authenticated
using (
    subido_por = public.get_current_internal_user_id()
    or public.is_admin_or_coordinator()
)
with check (
    subido_por = public.get_current_internal_user_id()
    or public.is_admin_or_coordinator()
);

create policy archivos_delete_owner_or_admin
on public.archivos
for delete
to authenticated
using (
    subido_por = public.get_current_internal_user_id()
    or public.is_admin()
);

create policy historial_select_staff
on public.historial_cambios
for select
to authenticated
using (public.is_admin_or_coordinator());

-- =========================================================
-- STORAGE
-- =========================================================

drop policy if exists storage_select_sigecom_archivos on storage.objects;
drop policy if exists storage_insert_sigecom_archivos on storage.objects;
drop policy if exists storage_update_sigecom_archivos on storage.objects;
drop policy if exists storage_delete_sigecom_archivos on storage.objects;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'sigecom-archivos',
    'sigecom-archivos',
    false,
    10485760,
    array[
        'application/pdf',
        'image/png',
        'image/jpeg',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    ]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy storage_select_sigecom_archivos
on storage.objects
for select
to authenticated
using (bucket_id = 'sigecom-archivos');

create policy storage_insert_sigecom_archivos
on storage.objects
for insert
to authenticated
with check (bucket_id = 'sigecom-archivos');

create policy storage_update_sigecom_archivos
on storage.objects
for update
to authenticated
using (
    bucket_id = 'sigecom-archivos'
    and (owner = auth.uid() or public.is_admin_or_coordinator())
)
with check (
    bucket_id = 'sigecom-archivos'
    and (owner = auth.uid() or public.is_admin_or_coordinator())
);

create policy storage_delete_sigecom_archivos
on storage.objects
for delete
to authenticated
using (
    bucket_id = 'sigecom-archivos'
    and (owner = auth.uid() or public.is_admin())
);

commit;
