-- Solicitudes de miembros para unirse a comisiones.
-- Ejecutar en Supabase SQL Editor despues de 001_sigecom_supabase.sql.

create table if not exists public.solicitudes_comision (
    id_solicitud bigint generated by default as identity primary key,
    id_comision bigint not null references public.comisiones (id_comision) on delete cascade,
    id_usuario bigint not null references public.usuarios (id_usuario) on delete cascade,
    mensaje text,
    estado varchar(20) not null default 'pendiente',
    fecha_solicitud timestamptz not null default now(),
    fecha_revision timestamptz,
    revisado_por bigint references public.usuarios (id_usuario),
    constraint solicitudes_comision_estado_chk check (estado in ('pendiente', 'aprobada', 'rechazada')),
    constraint solicitudes_comision_unica_pendiente unique (id_comision, id_usuario, estado)
);

create index if not exists idx_solicitudes_comision_id_comision
on public.solicitudes_comision (id_comision);

create index if not exists idx_solicitudes_comision_id_usuario
on public.solicitudes_comision (id_usuario);

alter table public.solicitudes_comision enable row level security;

drop policy if exists solicitudes_select_own_or_staff on public.solicitudes_comision;
create policy solicitudes_select_own_or_staff
on public.solicitudes_comision
for select
to authenticated
using (
    id_usuario = public.get_current_internal_user_id()
    or public.is_admin_or_coordinator()
);

drop policy if exists solicitudes_insert_own on public.solicitudes_comision;
create policy solicitudes_insert_own
on public.solicitudes_comision
for insert
to authenticated
with check (
    id_usuario = public.get_current_internal_user_id()
    and estado = 'pendiente'
);

drop policy if exists solicitudes_update_staff on public.solicitudes_comision;
create policy solicitudes_update_staff
on public.solicitudes_comision
for update
to authenticated
using (public.is_admin_or_coordinator())
with check (public.is_admin_or_coordinator());
