-- Solicitudes de presupuesto creadas por miembros de comisiones.
-- Ejecutar en Supabase SQL Editor despues de 001_sigecom_supabase.sql.

create table if not exists public.solicitudes_presupuesto (
    id_solicitud_presupuesto bigint generated by default as identity primary key,
    id_comision bigint not null references public.comisiones (id_comision) on delete cascade,
    id_usuario bigint not null references public.usuarios (id_usuario) on delete cascade,
    monto_solicitado numeric(12, 2) not null,
    justificacion text not null,
    estado varchar(20) not null default 'pendiente',
    fecha_solicitud timestamptz not null default now(),
    fecha_revision timestamptz,
    revisado_por bigint references public.usuarios (id_usuario),
    constraint solicitudes_presupuesto_monto_chk check (monto_solicitado > 0),
    constraint solicitudes_presupuesto_estado_chk check (estado in ('pendiente', 'aprobada', 'rechazada')),
    constraint solicitudes_presupuesto_unica_estado unique (id_comision, id_usuario, estado)
);

alter table public.solicitudes_presupuesto enable row level security;

drop policy if exists solicitudes_presupuesto_select_own_or_staff on public.solicitudes_presupuesto;
create policy solicitudes_presupuesto_select_own_or_staff
on public.solicitudes_presupuesto
for select
to authenticated
using (
    id_usuario = public.get_current_internal_user_id()
    or public.is_admin_or_coordinator()
);

drop policy if exists solicitudes_presupuesto_insert_member on public.solicitudes_presupuesto;
create policy solicitudes_presupuesto_insert_member
on public.solicitudes_presupuesto
for insert
to authenticated
with check (
    id_usuario = public.get_current_internal_user_id()
    and estado = 'pendiente'
    and public.is_comision_member(id_comision)
);

drop policy if exists solicitudes_presupuesto_update_staff on public.solicitudes_presupuesto;
create policy solicitudes_presupuesto_update_staff
on public.solicitudes_presupuesto
for update
to authenticated
using (public.is_admin_or_coordinator())
with check (public.is_admin_or_coordinator());

notify pgrst, 'reload schema';
